### ISSUE TITLE
Add rank column in the leaderboard

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#14]
Leaderboard is no fun without seeing the ranks of a person, add rank for each person, implement it in the most efficient way possible.

**Comment by kaneki-ken260** [comment]
claim

**Comment by MUKILAN-2003** [comment]
Claim
 I ready to work in in

**Comment by SeriousConjurer** [comment]
claim

**Comment by devmrfitz** [comment]
claim

**Comment by shubhajeet1207** [comment]
**CLAIM**
PLEASE ASSIGN ME THIS ISSUE.

**Comment by infern018** [comment]
Go ahead @criticic

**Comment by rankit2001** [comment]
claim

**Comment by Archit2002** [comment]
claim
