### ISSUE TITLE
Add background to make it look good

### ISSUE THREAD

**Issue by jen-sjen** [opencodeiiita/Leaderboard-Frontend#17]
Hey, I'm participating in hacktoberest2k21, please accept my issue. Good Day :)

**Comment by Mansivjain00** [comment]
hey, i would like to work on this!

**Comment by Mansivjain00** [comment]
claim

**Comment by kaneki-ken260** [comment]
claim

**Comment by The-Divyansh** [comment]
claim

**Comment by karankc23** [comment]
Claim

**Comment by naman-cr** [comment]
claim

**Comment by Palak-2109** [comment]
claim

**Comment by deep-ika** [comment]
claim

**Comment by deep-ika** [comment]
i want to work on it!!

**Comment by shivansh2741** [comment]
claim

**Comment by deep-ika** [comment]
Claim

**Comment by underoot-iota** [comment]
claim

**Comment by infern018** [comment]
@jen-sjen  no need for a background, we should keep the site as minimilastic as possible and I have planned some design changes for future too, closing this issue for now

**Comment by infern018** [comment]
Note : Issues which are not created by the mentor should not be claimed unless that mentor approves of it...!!!
