### ISSUE TITLE
Add Pagination to the leaderboard

### ISSUE THREAD

**Issue by batflarrow** [opencodeiiita/Leaderboard-Frontend#19]
Currently, there are about 550 users and it is taking a long time for all the user-rank list pairs to render, Pagination from the backend or the frontend is required. I would like to work on it.

**Comment by shlesh** [comment]
claim

**Comment by batflarrow** [comment]
> Currently, there are about 550 users and it is taking a long time for all the user-rank list pairs to render, Pagination from the backend or the frontend is required. I would like to work on it.

Major time taken is from the backend around 4 seconds, so most probably this will have to be implemented on the backend to make it more efficient.

**Comment by kaneki-ken260** [comment]
claim

**Comment by infern018** [comment]
> Currently, there are about 550 users and it is taking a long time for all the user-rank list pairs to render, Pagination from the backend or the frontend is required. I would like to work on it.

That's a great observation, even I was thinking of adding pagination in the future, can you state how will you proceed on implementing the pagination?

**Comment by batflarrow** [comment]
> > Currently, there are about 550 users and it is taking a long time for all the user-rank list pairs to render, Pagination from the backend or the frontend is required. I would like to work on it.
> 
> That's a great observation, even I was thinking of adding pagination in the future, can you state how will you proceed on implementing the pagination?

For pagination majorly what I had in mind to create the API itself to be paginated because as I could see currently major time is getting consumed in fetching the data so what I will do is create a paginated API that will have a page number in the API and in a single page fetch only top n users at a time and then when a user scrolls down page number will be incremented and then the api will fetch the next n users and display it. For calculating page numbers I will probably use the amount of scrolling a user has done.

**Comment by infern018** [comment]
> > > Currently, there are about 550 users and it is taking a long time for all the user-rank list pairs to render, Pagination from the backend or the frontend is required. I would like to work on it.
> > 
> > 
> > That's a great observation, even I was thinking of adding pagination in the future, can you state how will you proceed on implementing the pagination?
> 
> For pagination majorly what I had in mind to create the API itself to be paginated because as I could see currently major time is getting consumed in fetching the data so what I will do is create a paginated API that will have a page number in the API and in a single page fetch only top n users at a time and then when a user scrolls down page number will be incremented and then the api will fetch the next n users and display it. For calculating page numbers I will probably use the amount of scrolling a user has done.

Great thoughts but since this repo is for the frontend part only, I think modifying the API would be a viable option, hence we should come up with some get around using frontend only.

**Comment by batflarrow** [comment]
> > > > Currently, there are about 550 users and it is taking a long time for all the user-rank list pairs to render, Pagination from the backend or the frontend is required. I would like to work on it.
> > > 
> > > 
> > > That's a great observation, even I was thinking of adding pagination in the future, can you state how will you proceed on implementing the pagination?
> > 
> > 
> > For pagination majorly what I had in mind to create the API itself to be paginated because as I could see currently major time is getting consumed in fetching the data so what I will do is create a paginated API that will have a page number in the API and in a single page fetch only top n users at a time and then when a user scrolls down page number will be incremented and then the api will fetch the next n users and display it. For calculating page numbers I will probably use the amount of scrolling a user has done.
> 
> Great thoughts but since this repo is for the frontend part only, I think modifying the API would be a viable option, hence we should come up with some get around using frontend only.

If we talk about only frontend we can still implement pagination but it won't really reduce much time because major time is still being consumed in fetching the results, last I saw was about 4  seconds, we could just render stuff on the basis of scroll height as discussed earlier, it could save some milliseconds or a second if data increases further.

**Comment by infern018** [comment]
Update: @garvitchittora is already working on paginating the API, hence closing this for now, thanks for pointing out this issue @batflarrow , you can take the other issue which you mentioned.

**Comment by batflarrow** [comment]
> Update: @garvitchittora is already working on paginating the API, hence closing this for now, thanks for pointing out this issue @batflarrow , you can take the other issue which you mentioned.

Ohk great, Would love to work on the frontend implementation of the paginated API after it's done.
