### ISSUE TITLE
Add loader to the leaderboard page

### ISSUE THREAD

**Issue by batflarrow** [opencodeiiita/Leaderboard-Frontend#20]
Show a loader before the data is fetched and displayed on the page. I would like to work on this issue.

**Comment by deep-ika** [comment]
Claim

**Comment by kaneki-ken260** [comment]
claim

**Comment by schandu-eng** [comment]
i am interested to resolve this issue

**Comment by Amanverma1101** [comment]
> Show a loader before the data is fetched and displayed on the page. I would like to work on this issue.

Claim

**Comment by Amanverma1101** [comment]
claim

**Comment by Ksathwik03** [comment]
claim

**Comment by infern018** [comment]
@batflarrow go for it
