### ISSUE TITLE
BUG : Same points are reflecting different ranks

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#22]
Ranking is not implemented properly in the leaderboard, people having same points are showing different ranks, that should not be the case

## Screenshot
![image](https://user-images.githubusercontent.com/52378712/135830428-64c75bbe-9fdc-47f3-af8c-302ff8a8c896.png)

Please resolve it...

**Comment by shlesh** [comment]
claim

**Comment by infern018** [comment]
Take on @shlesh !!

**Comment by The-Divyansh** [comment]
claim

**Comment by kaneki-ken260** [comment]
claim

**Comment by hardikarora2** [comment]
claim

**Comment by jalanprakhar** [comment]
claim
