### ISSUE TITLE
Creating tables for leaderboard

### ISSUE THREAD

**Issue by Ksathwik03** [opencodeiiita/Leaderboard-Frontend#26]
![Screenshot_20211004-213010_Chrome](https://user-images.githubusercontent.com/76401429/135887546-2517a087-2cb7-415e-bf4d-4c96ee31991d.jpg)

I want to create tables similar to this with 2 columns name and score so that it can be easy to check the scores of the participants,Adding the hover method to the rows to provide a different color also helps in easily checking the score,I want to work on this .
Can you assign me to this issue sir .

**Comment by infern018** [comment]
Go ahead @Ksathwik03

**Comment by isharawat** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by Dheeraj096** [comment]
claim
