### ISSUE TITLE
Add favicon to the site

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#27]
Google and find some proper favicon to be added to the leaderboard

**Comment by shlesh** [comment]
Sir can we just add the opencode logo?
or something that resembles the theme(like asked in the task)

**Comment by infern018** [comment]
> Sir can we just add the opencode logo? or something that resembles the theme(like asked in the task)

Yeah that would be apt, go ahead..!!

**Comment by Amanverma1101** [comment]
Claim
