### ISSUE TITLE
Change background of top 3 contributors

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#28]
Make the background of row of top 3 contributors, i.e. with rank 1,2 and 3 respectively as Golden, Silver and Bronze, choose a light shade for these so that the contents are visible properly.

Feel free to continue this conversation or ping on discord for any query

**Comment by shlesh** [comment]
claim

**Comment by siddhantsingh186** [comment]
claim

**Comment by vemulapandu** [comment]
claim

**Comment by AgrimVerma** [comment]
claim

**Comment by isharawat** [comment]
Claim

**Comment by deep-ika** [comment]
claim

**Comment by Palak-2109** [comment]
claim

**Comment by deep-ika** [comment]
Claim

**Comment by prxtikk-18** [comment]
claim

**Comment by aka-sid** [comment]
CLAIM!!       Please assign this issue to me.

**Comment by MUKILAN-2003** [comment]
Claim

**Comment by rajraman786** [comment]
@infern018 it's done or not yet ? if not assign me I want to work on this .

**Comment by Amanverma1101** [comment]
Claim

**Comment by Ksathwik03** [comment]
> discord

Sir my last pull request was the same thing similar to this done i am just a few lines of code away from completing the issue so i request you to assign this to me.

**Comment by codesanta142** [comment]
claim

**Comment by sinifaa** [comment]
Claim

**Comment by infern018** [comment]
> > discord
> 
> Sir my last pull request was some thing similar to this done i am just a few lines of code away from completing the issue so i request you to assign this to me.

Its FCFS based, hence whoever claims first will get the issue
