### ISSUE TITLE
Adding pagination to the leaderboard

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#32]
We had some modifications in the API and had made it paginated, with the following template:

### Endpoint:
`/get-all-data/?page=<page_number>`

### Response:
```
{
    "start": "number: start index of the entries",
    "end": "number: end index of the entries",
    "page_number": "number: page number",
    "has_next": "boolean: next page available?",
    "has_prv": "boolean: previous page available?",
    "data": "array: entries of this page",
}
```

hence its now turn to add pagination in our frontend leaderboard too i.e. fetch only top few users at the start so that loading time is decreased and as user scrolls new ranks should keep getting displayed

A huge thanks to @garvitchittora  for setting up the API and credits to @batflarrow for already opening this #19 , you can follow the discussion there with him on implementing it and for any further queries.

Note : This won't be just a FCFS issue, you have to **mention how are you going to implement the pagination in this conversation**, the best solution will be assigned.

**Comment by batflarrow** [comment]
Claim

**Comment by ashutosh3027** [comment]
claim

**Comment by infern018** [comment]
As I mentioned just writing **claim** won't do you gotta mention how will you add pagination in frontend

**Comment by infern018** [comment]
Great approach @batflarrow , go for it, can you complete it by the end of the day if possible?

**Comment by batflarrow** [comment]
> Great approach @batflarrow , go for it, can you complete it by the end of the day if possible?

Yeah sure, which approach should I take different pages one or the scrolling one..?

**Comment by infern018** [comment]
scrolling one would do fine

**Comment by batflarrow** [comment]
> scrolling one would do fine

Cool

**Comment by batflarrow** [comment]
> scrolling one would do fine

Hey, @infern018  just had a question after implementing pagination the current ranking will break so should I fix it as well or save it for the future issue..?

**Comment by garvitchittora** [comment]
> > scrolling one would do fine
> 
> Hey, @infern018 just had a question after implementing pagination the current ranking will break so should I fix it as well or save it for the future issue..?

fix it as well!

@batflarrow But I don't get how the rank will break in this, Can you please share details on this?

**Comment by batflarrow** [comment]
> > > scrolling one would do fine
> > 
> > 
> > Hey, @infern018 just had a question after implementing pagination the current ranking will break so should I fix it as well or save it for the future issue..?
> 
> fix it as well!
> 
> @batflarrow But I don't get how the rank will break in this, Can you please share details on this?

The current implementation was using a set of the total scores and assigning ranks on the basis of unique scores, so when the next set of data was being fetched then the rank was again starting from 1 that's why it was breaking, anyways I fixed it now.

**Comment by infern018** [comment]
Great, thanks @batflarrow

**Comment by batflarrow** [comment]
> Great, thanks @batflarrow

I have made a pr you can review it.. #34

**Comment by batflarrow** [comment]
> Great, thanks @batflarrow

I have made a pr you can review it.. #34
