### ISSUE TITLE
Center the leaderboard section

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#35]
### Description
Only the header is centered correctly, the rest of the leaderboard isn't, pls resolve it

### Screenshot of problem:
![image](https://user-images.githubusercontent.com/52378712/135990774-52b795f6-430e-4aea-9714-aed3933e99b2.png)

### Note :
Don't use hardcoded margins or paddings please, figure out a generalise way such that its centered for all screens

**Comment by shlesh** [comment]
claim

**Comment by ashutosh3027** [comment]
claim

**Comment by karankc23** [comment]
claim

**Comment by MUKILAN-2003** [comment]
Claim

**Comment by raghavgoel25** [comment]
claim

**Comment by MUKILAN-2003** [comment]
I centered the Table by justify-content

![Screenshot from 2021-10-05 14-41-50](https://user-images.githubusercontent.com/65155327/135994920-f771cfda-0dd3-4849-b8f8-24a67137ea6e.png)

Claim

**Comment by naman-cr** [comment]
claim

**Comment by infern018** [comment]
@ashutosh3027  go for it

**Comment by infern018** [comment]
> Claim. I have Resolved the Issue. Can I make a PR

Already assigned to @ashutosh3027

**Comment by infern018** [comment]
@ashutosh3027  updates?, this one shouldn't take much time ig

**Comment by ashutosh3027** [comment]
@infern018 I have made pr one's review it
