### ISSUE TITLE
Magnifying rows on hover

### ISSUE THREAD

**Issue by Ksathwik03** [opencodeiiita/Leaderboard-Frontend#36]
As mentioned in pull request 30 , like the row appears a bit bigger or something on hover . I want to work on it sir. I will add the transitions this time to make it looker cleaner and easier for participants to check there score.

**Comment by isharawat** [comment]
Claim

**Comment by Ksathwik03** [comment]
@infern018 sir .

**Comment by infern018** [comment]
There is already an issue for beautifying the header, I'll look into this after that issue is closed
