### ISSUE TITLE
Knowing the score distribution.

### ISSUE THREAD

**Issue by Ksathwik03** [opencodeiiita/Leaderboard-Frontend#43]
My idea is to implement a onclick event when a user clicks on a particular name on the leaderboard then all the points from which the particular person in leaderboard had gained will visible. This helps in tracking the points which they scored and if an error occured it can be easily verified .

**Comment by Ksathwik03** [comment]
@infern018 sir 🥺

**Comment by infern018** [comment]
We will be having a separate page for that which leads to description of all the PRs created by a contributor, am working on that issue now and will open it soon...
