### ISSUE TITLE
Display More info for a contributor

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#67]
On hovering over a username, make a dropdown appear that shows a contributor's
 - Full Name
 - College
 - Enlarged image in a appropriate position too (in the dropdown itself)
 
 Make sure to style properly...

**Comment by shlesh** [comment]
sad

**Comment by Krishna3267** [comment]
Claim

**Comment by kaneki-ken260** [comment]
claim

**Comment by ashutosh3027** [comment]
claim

**Comment by infern018** [comment]
@Krishna3267  go for it
