### ISSUE TITLE
Design - CSS

### ISSUE THREAD

**Issue by SanskritiKushik5** [opencodeiiita/Leaderboard-Frontend#7]
It is very simple now, can I beautify it?

**Comment by infern018** [comment]
Sure @SanskritiKushik5, after the contribution period starts I'll assign it and you can start working ^^

**Comment by gokunik** [comment]
I would suggest to distribute it so that others can also work on it. 
I am looking forward to make contributions to this projects.

**Comment by infern018** [comment]
> I would suggest to distribute it so that others can also work on it. I am looking forward to make contributions to this project.

Yeah, this issue will be reopened once again in a distributed way, once we have some considerable amount of work on the site, closing it for now, looking fwd. to your contributions :)
