### ISSUE TITLE
Make issue and repo in details page as hyperlinks

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#71]
## Description
![image](https://user-images.githubusercontent.com/52378712/138210741-a262c8ce-71c2-495d-ae10-76fe9586d97c.png)

Currently in the details page, repo and issue are just displayed in plain texts, make them a hyperlink that will go to the GitHub page of the respective.

**Comment by VineethKumarM** [comment]
claim

**Comment by schandu-eng** [comment]
Claim
