### ISSUE TITLE
Center align all content and add a header logo at the top 

### ISSUE THREAD

**Issue by infern018** [opencodeiiita/Leaderboard-Frontend#8]
Currently all the content is left-aligned, place it in center and add a suitable header logo with appropriate header, you can use the opencode logo for that

**Comment by kaneki-ken260** [comment]
Thanks for the issue I would like to work on it!!

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by aashitachouhan** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by shlesh** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by Palak-2109** [comment]
wanna claim the issue

**Comment by Naman-11** [comment]
Claim, I want to work on this issue

**Comment by infern018** [comment]
Thanks for the amazing responses, but FCFS guys , @kaneki-ken260  go ahead...

**Comment by underoot-iota** [comment]
claim

**Comment by kaneki-ken260** [comment]
Thanks, @infern018 
Looking forward to work on this issue!!

**Comment by shadaanhussain** [comment]
I want this issue. Please assign it to me.

**Comment by Archit2002** [comment]
claim

**Comment by Nikita9344** [comment]
claim

**Comment by saloni33** [comment]
claim

**Comment by Shubhi2002** [comment]
Please assign this issue to me, I want to work on this issue...

**Comment by shivansh2741** [comment]
claim

**Comment by Anushh23** [comment]
Claim

**Comment by Perry0107** [comment]
claim

**Comment by codesanta142** [comment]
claim

**Comment by J-e-e-t** [comment]
claim

**Comment by MUKILAN-2003** [comment]
Claim

**Comment by james3gh** [comment]
claim

**Comment by J-e-e-t** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by Abhijeet452** [comment]
Claim

**Comment by aastha01chauhan** [comment]
claim, I want to work on this issue.

**Comment by sarikimohan** [comment]
claim

**Comment by hotblooded058** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by adtoria** [comment]
Claim

**Comment by deep-ika** [comment]
Thanks for the issue I would like to work on it!!

**Comment by 99anjali** [comment]
claim

**Comment by deep-ika** [comment]
Claim

**Comment by Yash091** [comment]
@garvitchittora sir, I had registered on the Devfolio but still it is showing not registered. Please consider this.
Thank you.

**Comment by rankit2001** [comment]
claim

**Comment by infern018** [comment]
> @garvitchittora sir, I had registered on the Devfolio but still it is showing not registered. Please consider this. Thank you.

Can you try on a new PR, if it works now?
